[package]
name = "api"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "api"

[dependencies]
actix = "0.12"
actix-web = "4.0.0-beta.13"
serde = "1.0"