[package]
name = "api"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "api"

[dependencies]
actix = "0.12.0"
actix-web = "4.0.0-beta.12"
#reqwest = "0"
serde = "1.0"
futures = "0.3"
#mongodb = { version = "2.0.1", features = ["tokio-runtime"] }
#bson = "2"
#redis = "*"
#chrono = "0"

[dev-dependencies]
actix-rt = "2.0.2"
tokio = "1"